### ISSUE TITLE
Syntax error in postgresql.conf

### ISSUE THREAD

**Issue by r9b9rt** [mattermost/mattermost-docker#83]
On master (5c9589dae046f92a273b8c2e4900dff1427df6bf) and team-and-enterprise (25a7c98f7547674852c3d1d3ca28e2720f2a60da) I'm getting syntax errors during `docker-compose up` for `/var/lib/postgresql/data/postgresql.conf`

I followed these steps: https://docs.mattermost.com/install/prod-docker.html

team-and-enterprise (25a7c98f7547674852c3d1d3ca28e2720f2a60da)
```Attaching to mattermostdocker_db_1, mattermostdocker_app_1, mattermostdocker_web_1
web_1  | Starting Nginx
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
app_1  | Configure database connection...SKIP
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
app_1  | Wait until database db:5432 is ready...
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
```

master (5c9589dae046f92a273b8c2e4900dff1427df6bf)
```db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 609, near end of line
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 610, near end of line
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors

**Comment by Niceplace** [comment]
Same here !
Will update if I find a fix.

**Comment by vitosans** [comment]
yeah I would agree. In the docker-entrypoint.sh in the db folder you could do: 

```
sed -i "s/archive_timeout =.*$/archive_timeout = $ARCHIVE_TIMEOUT/g" $PGDATA/postgresql.conf
```

But that only moves the ball forward for a second, then you get lots of other errors about missing tables and wal_e dies. Its to bad, I really wanted to evaluate this product for production usage but if I can't ever get the docker container to run I am off to find better solution.

**Comment by xcompass** [comment]
Thanks everyone for reporting this. This should be fixed by this commit https://github.com/mattermost/mattermost-docker/commit/4c30235fdefa16f5e9dd19c2a9a6699cf9647d4a. I'll update the images as well.

**Comment by xcompass** [comment]
@vitosans it is because postgres already past the initialisation stage, so it won't be able to create those tables. You can just remove postgres data files (if you don't have any data). They are under volumes/db if you are using docker-compose

**Comment by activedecay** [comment]
this is my problem, most likely. #31

**Comment by th3m4ri0** [comment]
Still have the error at 6c69e8299849d03aea2a65279e7098e1f5028312
```
db_1   |
db_1   | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/make_db.sh
db_1   | CREATE DATABASE
db_1   | CREATE ROLE
db_1   | GRANT
db_1   |
db_1   | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/setup-wale.sh
db_1   |
db_1   | LOG:  received fast shutdown request
db_1   | LOG:  aborting any active transactions
db_1   | waiting for server to shut down....LOG:  autovacuum launcher shutting down
db_1   | LOG:  shutting down
db_1   | LOG:  database system is shut down
db_1   |  done
db_1   | server stopped
db_1   |
db_1   | PostgreSQL init process complete; ready for start up.
db_1   |
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 609, near end of line
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 610, near end of line
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors
db_1   | AWS_ACCESS_KEY_ID is required for Wal-E but not set. Skipping Wal-E setup.
db_1   | LOG:  syntax error in file "/var/lib/postgresql/data/postgresql.conf" line 612, near end of line
db_1   | FATAL:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors```

**Comment by activedecay** [comment]
I'm not a maintainer, but I would say wait for next release

**Comment by th3m4ri0** [comment]
@activedecay the patch was already released on master (4c30235fdefa16f5e9dd19c2a9a6699cf9647d4a) and the issue is still here.

**Comment by xcompass** [comment]
@th3m4ri0 Does it work now?

**Comment by th3m4ri0** [comment]
It does ! Sorry for the trouble.

**Comment by xcompass** [comment]
No worries.

**Comment by Californian** [comment]
For anyone who is still experiencing the issue, it's probably because the `team-and-enterprise` branch doesn't have this patch yet; go to https://github.com/mattermost/mattermost-docker/commit/4c30235fdefa16f5e9dd19c2a9a6699cf9647d4a and copy-paste the patch yourself, run `docker-compose build` and `docker-compose up -d` and you should be all set.
